import { PastryItem } from './types';

export const BAKER_INFO = {
  name: 'Damilola Omotayo',
  businessName: 'Crunchy Crispy Chin Chin',
  shortName: 'Dammy Crunchy',
  email: 'omotayodamilola762@gmail.com',
  phoneDisplay: '+234 911 781 4369',
  whatsappNumber: '2349117814369',
  tagline: 'Crunchy Crispy Chin Chin, Fluffy Donuts, Crispy Egg Rolls & Custom Flour Pastries',
  orderLeadTime: '24-48 hours for small batches · 3-5 days for bulk party catering',
  location: 'Fresh Kitchen Baking · Home Delivery & Event Venue Drop-off',
};

export const PASTRIES_CATALOG: PastryItem[] = [
  {
    id: 'chin-chin-classic',
    title: 'Golden Signature Chin Chin',
    category: 'chin-chin',
    categoryLabel: 'Crunchy Chin Chin',
    tagline: 'Melt-in-your-mouth crunch with rich Madagascar vanilla & sweet nutmeg',
    description: 'Our pride and joy. Rolled by hand, cut into crisp bite-sized morsels, and fried to golden amber perfection. Stays crunchy for up to 6 months in our airtight seals. Available in personal snack pouches all the way to 10-litre celebration tubs.',
    image: '/images/chin_chin.jpg',
    fallbackGradient: 'from-amber-700 to-yellow-600',
    flavors: ['Classic Vanilla & Nutmeg', 'Sweet Toasted Coconut', 'Cinnamon Spice', 'Peppered Savory Crunch (Party Favorite)'],
    ingredients: ['Enriched Wheat Flour', 'Pure Creamery Butter', 'Evaporated Milk', 'Cane Sugar', 'Nutmeg & Vanilla', 'Eggs', 'Vegetable Oil'],
    shelfLife: '6 months (when sealed in cool, dry place)',
    isPopular: true,
    isBulkAvailable: true,
    bakingMethod: 'Crispy Fried',
    variants: [
      {
        id: 'cc-pouch-250',
        name: 'Snack Pouch (250g)',
        description: 'Perfect personal crunch for movie nights, desk snacking, or lunch boxes',
        priceNGN: 1500,
        priceUSD: 3.50,
        priceGBP: 2.80,
        weightOrUnit: '250g resealable foil zip pouch',
        recommendedFor: '1-2 people',
        isBulk: false,
      },
      {
        id: 'cc-tub-500',
        name: 'Table Tub (500g)',
        description: 'Generous airtight tub ideal for pantry, family snacking, and guest treats',
        priceNGN: 2800,
        priceUSD: 6.50,
        priceGBP: 5.20,
        weightOrUnit: '500g airtight food container',
        recommendedFor: 'Family & sharing',
        isBulk: false,
      },
      {
        id: 'cc-jar-1kg',
        name: 'Family Jar (1kg)',
        description: 'Our most popular household size. Keeps freshly crispy for months',
        priceNGN: 5200,
        priceUSD: 12.00,
        priceGBP: 9.50,
        weightOrUnit: '1kg durable clear pantry jar',
        recommendedFor: 'Households & gift hampers',
        isBulk: false,
      },
      {
        id: 'cc-bucket-5l',
        name: 'Party Bucket (5 Litres)',
        description: 'Heavyweight celebration bucket for birthdays, bridal showers & office socials',
        priceNGN: 22000,
        priceUSD: 48.00,
        priceGBP: 38.00,
        weightOrUnit: '5-Litre sealed handle bucket (~3.2kg)',
        recommendedFor: '20-35 guests',
        isBulk: true,
      },
      {
        id: 'cc-tub-10l',
        name: 'Grand Event Tub (10 Litres)',
        description: 'Wholesale event giant tub for weddings, mega parties, church conventions & banquets',
        priceNGN: 42000,
        priceUSD: 90.00,
        priceGBP: 72.00,
        weightOrUnit: '10-Litre bulk catering drum (~6.5kg)',
        recommendedFor: '60-100+ guests',
        isBulk: true,
      },
      {
        id: 'cc-souvenir-20',
        name: 'Wedding & Party Souvenirs (20 mini jars)',
        description: '20 individually tied clear jars with custom ribbon and thank-you tags',
        priceNGN: 28000,
        priceUSD: 62.00,
        priceGBP: 49.00,
        weightOrUnit: '20 customized 150g souvenir jars',
        recommendedFor: 'Wedding / birthday guest favors',
        isBulk: true,
      },
    ],
  },
  {
    id: 'artisan-donuts',
    title: 'Fluffy Artisan Glazed Donuts',
    category: 'donuts',
    categoryLabel: 'Artisan Donuts',
    tagline: 'Pillowy, cloud-soft yeast donuts fried fresh every morning',
    description: 'Light, airy, and delicately sweetened. Hand-shaped and fried to a golden hue, then topped with your choice of warm vanilla bean glaze, silky Belgian chocolate drizzle, cinnamon sugar dust, or fruit jams. Baked fresh on the day of your event.',
    image: '/images/donuts.jpg',
    fallbackGradient: 'from-amber-600 to-orange-500',
    flavors: ['Classic Vanilla Bean Glaze', 'Rich Dark Chocolate Drizzle', 'Cinnamon Sugar Dust', 'Strawberry Jam Core', 'Nutty Roasted Coconut', 'Assorted Party Box Mix'],
    ingredients: ['High-Grade Flour', 'Pure Butter', 'Fresh Milk', 'Active Yeast', 'Free-Range Eggs', 'Vanilla Bean Paste', 'Glaze Syrups'],
    shelfLife: 'Best enjoyed within 24-48 hours',
    isPopular: true,
    isBulkAvailable: true,
    bakingMethod: 'Freshly Fried',
    variants: [
      {
        id: 'donut-half-dozen',
        name: 'Baker’s Half Dozen (6 Pcs)',
        description: 'Six warm, fresh artisan donuts with your pick of glazes and toppings',
        priceNGN: 5000,
        priceUSD: 10.50,
        priceGBP: 8.50,
        weightOrUnit: 'Custom 6-slot bakery box',
        recommendedFor: 'Couples & small cravings',
        isBulk: false,
      },
      {
        id: 'donut-dozen',
        name: 'Artisan Dozen (12 Pcs)',
        description: 'Twelve assorted melt-in-your-mouth donuts. Ideal for family breakfast or meetings',
        priceNGN: 9500,
        priceUSD: 19.50,
        priceGBP: 15.50,
        weightOrUnit: '12-piece presentation box',
        recommendedFor: 'Family & team meetings',
        isBulk: false,
      },
      {
        id: 'donut-party-24',
        name: 'Party Platter Box (24 Pcs)',
        description: 'Vibrant assortment of glazed, iced, and dusted donuts ready to wow party guests',
        priceNGN: 18000,
        priceUSD: 38.00,
        priceGBP: 30.00,
        weightOrUnit: '24-piece catering platter',
        recommendedFor: '15-25 guests',
        isBulk: true,
      },
      {
        id: 'donut-tower-50',
        name: 'Event Mini-Donut Tower (50 Pcs)',
        description: '50 gourmet bite-sized glazed donuts designed for dessert tables and celebration displays',
        priceNGN: 35000,
        priceUSD: 75.00,
        priceGBP: 60.00,
        weightOrUnit: '50-piece event catering kit',
        recommendedFor: '40-60 guests',
        isBulk: true,
      },
    ],
  },
  {
    id: 'nigerian-egg-rolls',
    title: 'Traditional Golden Egg Rolls',
    category: 'egg-rolls',
    categoryLabel: 'Golden Egg Rolls',
    tagline: 'Whole seasoned boiled egg wrapped in sweet-savory golden pastry crust',
    description: 'The authentic West African bakery classic. We start with farm-fresh hard-boiled eggs, delicately seasoned, then encased in a thick, slightly sweet and fragrant dough. Fried slow and steady until the crust turns deeply golden and crisp outside while remaining soft inside.',
    image: '/images/egg_rolls.jpg',
    fallbackGradient: 'from-yellow-700 to-amber-600',
    flavors: ['Classic Sweet-Savory Crust', 'Nutmeg & Mild Black Pepper Herb', 'Spicy Pepper Blend'],
    ingredients: ['Fresh Hard-Boiled Eggs', 'Enriched Pastry Flour', 'Butter', 'Evaporated Milk', 'Nutmeg', 'Pure Cane Sugar', 'Sea Salt'],
    shelfLife: 'Best consumed within 24-48 hours (reheats crisp in air fryer/oven)',
    isPopular: true,
    isBulkAvailable: true,
    bakingMethod: 'Crispy Fried',
    variants: [
      {
        id: 'eggroll-duo',
        name: 'Duo Pack (2 Large Rolls)',
        description: 'Two hefty, golden egg rolls. Satisfying and deeply flavorful',
        priceNGN: 2000,
        priceUSD: 4.50,
        priceGBP: 3.50,
        weightOrUnit: '2 large whole-egg pastries',
        recommendedFor: 'Personal quick meal',
        isBulk: false,
      },
      {
        id: 'eggroll-six',
        name: 'Half Dozen Pack (6 Pcs)',
        description: 'Six warm golden egg rolls in a bakery insulated box',
        priceNGN: 5500,
        priceUSD: 12.00,
        priceGBP: 9.80,
        weightOrUnit: '6-piece insulated box',
        recommendedFor: 'Family tea time / road trips',
        isBulk: false,
      },
      {
        id: 'eggroll-party-12',
        name: 'Party Box (12 Pcs)',
        description: 'Twelve jumbo golden egg rolls for brunch gatherings, picnics, and meetings',
        priceNGN: 10500,
        priceUSD: 22.50,
        priceGBP: 18.00,
        weightOrUnit: '12-piece banquet box',
        recommendedFor: '10-15 people',
        isBulk: true,
      },
      {
        id: 'eggroll-event-30',
        name: 'Event Buffet Tray (30 Pcs)',
        description: 'Thirty freshly fried egg rolls packed hot for party buffets and small chops stations',
        priceNGN: 26000,
        priceUSD: 55.00,
        priceGBP: 44.00,
        weightOrUnit: '30-piece food service tray',
        recommendedFor: '25-35 guests',
        isBulk: true,
      },
      {
        id: 'eggroll-bulk-60',
        name: 'Wholesale Catering Tub (60 Pcs)',
        description: 'Sixty pieces prepared for large wedding receptions, church luncheons, and corporate catering',
        priceNGN: 50000,
        priceUSD: 105.00,
        priceGBP: 84.00,
        weightOrUnit: '60-piece heavy catering box',
        recommendedFor: '50-70 guests',
        isBulk: true,
      },
    ],
  },
  {
    id: 'flaky-meat-pie',
    title: 'Nigerian Flaky Meat Pies & Chicken Pies',
    category: 'savory-chops',
    categoryLabel: 'Savory & Small Chops',
    tagline: 'Ultra-flaky buttery pastry stuffed with seasoned minced beef, potatoes & carrots',
    description: 'Baked to golden brown with a flaky, buttery shortcrust that melts in your mouth without crumbling apart. Filled generously with savory minced beef, diced Irish potatoes, carrots, and aromatic thyme & curry spices. Also available with tender chicken filling.',
    image: '/images/hero.jpg',
    fallbackGradient: 'from-stone-700 to-amber-800',
    flavors: ['Classic Seasoned Minced Beef', 'Tender Curried Chicken', 'Spicy Peppered Beef'],
    ingredients: ['Pure Butter Pastry Dough', 'Lean Minced Beef / Chicken', 'Irish Potatoes', 'Sweet Carrots', 'Thyme, Curry & Garlic', 'Rich Meat Broth'],
    shelfLife: '3-4 days refrigerated; reheats to oven-fresh crispness',
    isPopular: true,
    isBulkAvailable: true,
    bakingMethod: 'Slow Baked',
    variants: [
      {
        id: 'pie-box-6',
        name: 'Half Dozen Pies (6 Pcs)',
        description: 'Six golden, piping hot flaky meat or chicken pies',
        priceNGN: 6500,
        priceUSD: 14.00,
        priceGBP: 11.00,
        weightOrUnit: '6-piece pastry bakery box',
        recommendedFor: '3-6 people',
        isBulk: false,
      },
      {
        id: 'pie-box-12',
        name: 'Baker’s Dozen Pies (12 Pcs)',
        description: 'Twelve jumbo meat pies for office lunches, weekend treats, and parties',
        priceNGN: 12500,
        priceUSD: 26.50,
        priceGBP: 21.00,
        weightOrUnit: '12-piece catering box',
        recommendedFor: 'Office & family gatherings',
        isBulk: true,
      },
      {
        id: 'pie-event-30',
        name: 'Event Catering Tray (30 Pcs)',
        description: 'Thirty golden flaky pies for wedding buffets, conference lunches & parties',
        priceNGN: 30000,
        priceUSD: 64.00,
        priceGBP: 51.00,
        weightOrUnit: '30-piece insulated catering flat',
        recommendedFor: '30+ guests',
        isBulk: true,
      },
    ],
  },
  {
    id: 'sweet-puff-puff',
    title: 'Pillowy Golden Puff Puff',
    category: 'savory-chops',
    categoryLabel: 'Savory & Small Chops',
    tagline: 'Sweet, chewy, golden fried dough spheres with subtle nutmeg fragrance',
    description: 'The heartbeat of every celebration. Our puff puff is delightfully crisp on the outside, tender and chewy on the inside, and never greasy. Made with fresh yeast batter and warm spices. Available in spiced sweet or chili-flecked party style.',
    image: '/images/hero.jpg',
    fallbackGradient: 'from-amber-600 to-yellow-700',
    flavors: ['Classic Sweet & Nutmeg', 'Cinnamon Sugar Coated', 'Mildly Peppered Party Style'],
    ingredients: ['Flour', 'Active Yeast', 'Pure Cane Sugar', 'Warm Spices & Nutmeg', 'Spring Water', 'Vegetable Oil'],
    shelfLife: 'Best consumed fresh on day of delivery',
    isPopular: false,
    isBulkAvailable: true,
    bakingMethod: 'Freshly Fried',
    variants: [
      {
        id: 'puff-snack-20',
        name: 'Snack Tub (20 Pcs)',
        description: 'Twenty bite-sized golden sweet puff puff spheres',
        priceNGN: 2200,
        priceUSD: 5.00,
        priceGBP: 4.00,
        weightOrUnit: '20 pieces in heat-sealed tub',
        recommendedFor: 'Personal / movie snacks',
        isBulk: false,
      },
      {
        id: 'puff-party-60',
        name: 'Party Bowl (60 Pcs)',
        description: 'Sixty golden puff puffs for birthdays, game nights, and home feasts',
        priceNGN: 6500,
        priceUSD: 14.00,
        priceGBP: 11.20,
        weightOrUnit: '60 pieces in catering bowl',
        recommendedFor: '10-15 people',
        isBulk: true,
      },
      {
        id: 'puff-event-180',
        name: 'Grand Event Drum (180 Pcs)',
        description: 'Large catering batch for wedding small-chops stations and banquets',
        priceNGN: 18000,
        priceUSD: 39.00,
        priceGBP: 31.00,
        weightOrUnit: '180 pieces in insulated banquet bucket',
        recommendedFor: '40-60 guests',
        isBulk: true,
      },
    ],
  },
  {
    id: 'flaky-sausage-fish-rolls',
    title: 'Flaky Sausage Rolls & Fish Rolls',
    category: 'savory-chops',
    categoryLabel: 'Savory & Small Chops',
    tagline: 'Buttery rolled pastry packed with seasoned sausage meat or spiced mackerel',
    description: 'Golden, crumbly rolled pastries made from our scratch-made butter dough. Choose between savory seasoned beef sausage filling or spiced, aromatic smoked fish and herb filling.',
    image: '/images/hero.jpg',
    fallbackGradient: 'from-yellow-800 to-stone-700',
    flavors: ['Classic Beef Sausage Roll', 'Spiced Fish Roll (Mackerel & Herbs)', 'Spicy Pepper Sausage Roll'],
    ingredients: ['Pastry Flour', 'Butter', 'Seasoned Beef Sausage / Mackerel Fish', 'Onions & Herbs', 'Egg Glaze'],
    shelfLife: '3 days refrigerated; warms wonderfully in toaster/air fryer',
    isPopular: false,
    isBulkAvailable: true,
    bakingMethod: 'Slow Baked',
    variants: [
      {
        id: 'rolls-pack-6',
        name: 'Pack of 6 Rolls',
        description: 'Six freshly baked flaky pastry rolls',
        priceNGN: 3500,
        priceUSD: 7.50,
        priceGBP: 6.00,
        weightOrUnit: '6 pieces in pastry box',
        recommendedFor: 'Snacking on the go',
        isBulk: false,
      },
      {
        id: 'rolls-party-20',
        name: 'Party Platter (20 Pcs)',
        description: 'Twenty golden rolls sliced into party fingers or served whole',
        priceNGN: 11000,
        priceUSD: 24.00,
        priceGBP: 19.00,
        weightOrUnit: '20-piece party tray',
        recommendedFor: 'Party finger-food',
        isBulk: true,
      },
      {
        id: 'rolls-event-50',
        name: 'Banquet Tray (50 Pcs)',
        description: 'Fifty flaky pastry rolls for large gatherings and events',
        priceNGN: 26000,
        priceUSD: 56.00,
        priceGBP: 45.00,
        weightOrUnit: '50-piece catering tray',
        recommendedFor: '50+ guests',
        isBulk: true,
      },
    ],
  },
];

export const BULK_EVENT_PACKS = [
  {
    id: 'combo-wedding-delight',
    name: 'Royal Wedding Souvenir & Cocktail Combo',
    recommendedGuests: '100 - 150 Guests',
    contents: '50 Custom Chin Chin Souvenir Jars + 60 Golden Egg Rolls + 80 Artisan Donut Platter + 100 Flaky Meat Pie Fingers',
    discountPercent: 15,
    estimatedPriceNGN: 125000,
    estimatedPriceUSD: 270,
    estimatedPriceGBP: 215,
    highlight: 'Includes custom branded labels and ribbon ties',
  },
  {
    id: 'combo-birthday-bash',
    name: 'Celebration Birthday Bash Pack',
    recommendedGuests: '40 - 60 Guests',
    contents: '1x 5L Chin Chin Bucket + 24 Artisan Glazed Donuts + 30 Golden Egg Rolls + 60 Sweet Puff Puff',
    discountPercent: 10,
    estimatedPriceNGN: 68000,
    estimatedPriceUSD: 148,
    estimatedPriceGBP: 118,
    highlight: 'Ideal mix of sweet, crunchy, and savory bites',
  },
  {
    id: 'combo-church-social',
    name: 'Church & Community Fellowship Feast',
    recommendedGuests: '80 - 120 Guests',
    contents: '1x 10L Giant Chin Chin Tub + 48 Assorted Donuts + 60 Crispy Egg Rolls',
    discountPercent: 12,
    estimatedPriceNGN: 98000,
    estimatedPriceUSD: 212,
    estimatedPriceGBP: 169,
    highlight: 'Feeds a crowd affordably with maximum crowd satisfaction',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Adebayo & Funke Ogundimu',
    role: 'Wedding Clients',
    event: 'Wedding Reception (300 Guests)',
    quote: 'Privilege made 250 custom-tied chin chin jars and egg rolls for our wedding favors in Lekki. Our guests literally emptied the souvenir tables in 10 minutes! The chin chin crunch was out of this world.',
    rating: 5,
  },
  {
    name: 'Mrs. Chidinma Eze',
    role: 'Event Planner & Coordinator',
    event: '50th Birthday Banquet',
    quote: 'As an event planner, reliability is everything. Privy FlourCraft delivered 100 egg rolls and 3 bulk buckets of chin chin hot, fresh, and packaged neatly on time. My go-to flour treats baker!',
    rating: 5,
  },
  {
    name: 'Tunde Bakare',
    role: 'Office Operations Lead',
    event: 'Monthly Corporate Town Hall',
    quote: 'The glazed donuts and meat pies disappeared faster than our quarterly presentation. The crust on the pies is real butter flakiness, not doughy like regular fast-food pies.',
    rating: 5,
  },
];

export const FAQS = [
  {
    q: 'How far in advance should I place bulk and event orders?',
    a: 'For retail orders and snack packs (1 to 5 items), 24 to 48 hours notice is sufficient. For bulk orders, party buckets, and events with 50+ guests, we recommend 3 to 7 days advance notice to guarantee custom packaging and morning-of-event fresh frying.',
  },
  {
    q: 'What is the secret to keeping your chin chin so crunchy?',
    a: 'We use a time-tested technique with real creamery butter, evaporated milk, and precise slow temperature frying. Once opened, keep your chin chin in an airtight plastic or glass jar at room temperature. It will stay ultra-crisp for up to 6 months!',
  },
  {
    q: 'Can you cater "anything flour can make" outside the listed menu?',
    a: 'Yes! That is our exact promise. If flour, butter, yeast, and love can make it — from special braided sweet breads, savory meat pies, chicken turnovers, samosas, spring rolls, to custom cinnamon rolls or specialty donut glazes — simply reach out via our Custom Pastry Studio or WhatsApp.',
  },
  {
    q: 'How do I place my order or discuss bulk pricing options?',
    a: 'You can build your order right here on the website! Add items to your bag or use our Bulk Calculator. When ready, click "Send via WhatsApp" or "Submit Inquiry" to connect directly with Chef Privilege Oyegbile (privilegeoyegbile@gmail.com). We will confirm your delivery date, payment terms, and delivery address immediately.',
  },
  {
    q: 'Do you offer custom branding for event souvenirs?',
    a: 'Yes! For weddings, anniversaries, and brand launches, we offer personalized stickers with your couple names, wedding hashtags, company logos, and themed ribbons on jars and pouches.',
  },
];
